[package]
name = "sandpile_fractal"
version = "0.1.0"
authors = ["Elliott Mahler <emahler@usc.edu>"]
edition = "2018"

[dependencies]
image = "*"
rayon = "*"
serde = "*"
serde_derive = "*"
bincode = "*"
